consul:
  host: localhost
  port: 8500
service:
  discoveryHost: localhost
  healthCheck:
    timeout: 1s
    interval: 10s
  maxRetry: 5
  retryInterval: 5000
  id: null
  name: nestcloud-typeorm-example-service
  port: 8081
config:
  name: nestcloud-typeorm-example-service-config
dataSource:
  host: localhost
  port: 3306
  username: root
  password: Passw0rd
  synchronize: true
  maxQueryExecutionTime: 1000
loadbalance:
  rule: RandomRule
  services:
    - name: your-service-name
      rule: RoundRobinRule
logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: nestcloud-user-service
    - transport: file
      name: info
      json: false
      filename: ../logs/all.log
      datePattern: YYYY-MM-DD h:mm:ss
      label: nestcloud-starter-service
      # 200M
      maxsize: 209715200
      maxFiles: 10
    - transport: file
      name: error
      level: error
      json: false
      filename: ../logs/error.log
      datePattern: YYYY-MM-DD h:mm:ss
      label: nestcloud-starter-service
      # 200M
      maxsize: 209715200
      maxFiles: 10
